dBug: dBug Class Reference
dBug Class Reference
Public Member Functions
dBug ($var, $forceType="", $bCollapsed=false)
getVariableName ()
initializeHeader (&$header)
error ($type)
prints error
checkType ($var)
check variable type andd process the value in right way
xmlDefaultHandler ($parser, $data)
xml: initiated when a comment or other miscellaneous texts is encountered
rendering functions
used to make tables representing different variables
makeTableHeader ($type, $header, $colspan=2)
creates the main table header
renderTableHeader ($type, $text, $colspan=0)
draws the main table header
renderPrimitiveType ($headerStyle, $header, $value, $valueStyle=null, $colspan=0)
renders table of 2 cells in 1 row [type][value]
makeTDHeader ($type, $header)
creates the table row header
closeTDRow ()
closes table row
functions for rendering different types
varIsNULL ()
renders NULL as red-pink rectangle
varIsNumeric ($var, $type)
renders numeric types : integers and doubles
varIsString (&$var)
renders string either as primitive type (if it is short (less than $embeddedStringMaxLength chars) and contains of one line) or line-by-line (otherwise)
varIsBoolean (&$var)
renders boolean variable
varIsArray (&$var)
varIsObject (&$var)
checks wheither variable is object of special type (using varIs*Object), and renders it if it is generic object
varIsSpecialObject (&$var)
varIsResource ($var)
shows info about different resources, uses customized rendering founctions when needed
functions for rendering different resources
varIsCurlEasyResource (&$var)
shows information about curl easy handles
varIsCurlMultiResource (&$var)
not implemented yet
varIsGDResource ($var)
if variable is an image/gd resource type
database results rendering functions
varIsDBObject ($var)
renders either PDO or SQLite3 statement objects
renderDBData (&$objectType, &$structure, &$data)
renders database data
varIsDBResource ($var, $db='mysql')
renders database resource (fetch result) into table or ... smth else
xml rendering functions
varIsXml ($var)
if variable is an xml type remember, that you must force type to xml to use this
varIsXmlResource ($var)
if variable is an xml resource type
xmlParse ($xml_parser, $data, $bFinal)
parses xml
xmlStartElement ($parser, $name, $attribs)
xml: inititiated when a start tag is encountered
xmlEndElement ($parser, $name)
xml: initiated when an end tag is encountered
xmlCharacterData ($parser, $data)
xml: initiated when text between tags is encountered
Static Public Member Functions
static initJSandCSS ()
adds needed JS and CSS sources to page
Data Fields
$xmlDepth =array()
$xmlCData
$xmlSData
$xmlDData
$xmlCount =0
$xmlAttrib
$xmlName
$bInitialized = false
shows wheither the main header for this dBug call was drawn
$bCollapsed = false
$arrHistory = array()
Static Public Attributes
static $embeddedStringMaxLength =50
other special kinds of objects rendering functionality
static $exceptionMainProps =array('message','code','file','line')
array of properties of every exception to be rendered first
static $exceptionExcludedProps
array of properties of Exception of not to be rendered
varIsException (&$var)
function used to render exceptions
Detailed Description
Author
ospinto
KOLANICH
Definition at line 28 of file dBug.php.
Member Function Documentation
checkType ($var)
check variable type andd process the value in right way
Definition at line 179 of file dBug.php.
References varIsArray(), varIsBoolean(), varIsNULL(), varIsNumeric(), varIsObject(), varIsResource(), and varIsString().
Referenced by dBug(), varIsArray(), varIsCurlEasyResource(), varIsException(), varIsGDResource(), and varIsObject().
closeTDRow ()
closes table row
Definition at line 163 of file dBug.php.
Referenced by varIsArray(), varIsCurlEasyResource(), varIsException(), varIsGDResource(), varIsObject(), varIsResource(), and varIsString().
dBug ($var, $forceType = "", $bCollapsed = false)
Parameters
mixed $var Variable to dump
string $forceType type to marshall $var to show
boolean $bCollapsed should output be collapsed
Definition at line 50 of file dBug.php.
References $bCollapsed, and checkType().
error ($type)
prints error
Definition at line 170 of file dBug.php.
getVariableName ()
Definition at line 65 of file dBug.php.
Referenced by initializeHeader().
initializeHeader (& $header)
Definition at line 95 of file dBug.php.
References getVariableName().
Referenced by makeTableHeader(), and renderPrimitiveType().
static initJSandCSS () static
adds needed JS and CSS sources to page
Definition at line 729 of file dBug.php.
makeTableHeader ($type, $header, $colspan = 2)
creates the main table header
Parameters
string $type name of the style of the header cell
string $header the text of the header cell
integer $colspan colspan property for the header cell
Definition at line 114 of file dBug.php.
References initializeHeader(), and renderTableHeader().
Referenced by renderDBData(), varIsArray(), varIsCurlEasyResource(), varIsDBResource(), varIsException(), varIsGDResource(), varIsNULL(), varIsObject(), varIsResource(), and varIsString().
makeTDHeader ($type, $header)
creates the table row header
Parameters
string $type name of the style of the key cell
string $header the text of the key cell
Definition at line 156 of file dBug.php.
Referenced by varIsArray(), varIsCurlEasyResource(), varIsException(), varIsGDResource(), varIsObject(), and varIsString().
renderDBData (& $objectType, & $structure, & $data)
renders database data
Parameters
string $objectType type of the db, it is only the name of header now
array $structure 'header' of the table - columns names and types
array $data rows of sql request result
Definition at line 494 of file dBug.php.
References makeTableHeader().
Referenced by varIsDBObject().
renderPrimitiveType ($headerStyle, $header, $value, $valueStyle = null, $colspan = 0)
renders table of 2 cells in 1 row [type][value]
Parameters
string $headerStyle name of the style of the header cell
string $header the text of the header cell
string $value the text of the value cell
string $valueStyle name of the style of the value cell
integer $colspan colspan property for the header cell
Definition at line 140 of file dBug.php.
References $bCollapsed, and initializeHeader().
Referenced by varIsBoolean(), varIsNumeric(), and varIsString().
renderTableHeader ($type, $text, $colspan = 0)
draws the main table header
Parameters
string $type name of the style of the header cell
string $text the text of the header cell
integer $colspan colspan property for the header cell
Definition at line 125 of file dBug.php.
References $bCollapsed.
Referenced by makeTableHeader().
varIsArray (& $var)
Definition at line 262 of file dBug.php.
References checkType(), closeTDRow(), makeTableHeader(), and makeTDHeader().
Referenced by checkType().
varIsBoolean (& $var)
renders boolean variable
Definition at line 256 of file dBug.php.
References renderPrimitiveType().
Referenced by checkType().
varIsCurlEasyResource (& $var)
shows information about curl easy handles
simply iterates through handle info and displays everything which is not converted into false
Definition at line 388 of file dBug.php.
References checkType(), closeTDRow(), makeTableHeader(), and makeTDHeader().
Referenced by varIsResource().
varIsCurlMultiResource (& $var)
not implemented yet
Definition at line 404 of file dBug.php.
varIsDBObject ($var)
renders either PDO or SQLite3 statement objects
Returns
1 if the object is DB object, 0 otherwise
Definition at line 440 of file dBug.php.
References renderDBData().
Referenced by varIsSpecialObject().
varIsDBResource ($var, $db = 'mysql')
renders database resource (fetch result) into table or ... smth else
Definition at line 518 of file dBug.php.
References makeTableHeader().
Referenced by varIsResource().
varIsException (& $var)
function used to render exceptions
Renders exceptions : at first basic fields, then custom fields. Custom private and protected fields are rendered if reflection api is available
Definition at line 581 of file dBug.php.
References checkType(), closeTDRow(), makeTableHeader(), and makeTDHeader().
Referenced by varIsSpecialObject().
varIsGDResource ($var)
if variable is an image/gd resource type
Definition at line 409 of file dBug.php.
References checkType(), closeTDRow(), makeTableHeader(), and makeTDHeader().
Referenced by varIsResource().
varIsNULL ()
renders NULL as red-pink rectangle
Definition at line 217 of file dBug.php.
References makeTableHeader().
Referenced by checkType().
varIsNumeric ($var, $type)
renders numeric types : integers and doubles
Definition at line 223 of file dBug.php.
References renderPrimitiveType().
Referenced by checkType().
varIsObject (& $var)
checks wheither variable is object of special type (using varIs*Object), and renders it if it is generic object
Definition at line 295 of file dBug.php.
References checkType(), closeTDRow(), makeTableHeader(), makeTDHeader(), and varIsSpecialObject().
Referenced by checkType().
varIsResource ($var)
shows info about different resources, uses customized rendering founctions when needed
Definition at line 345 of file dBug.php.
References closeTDRow(), makeTableHeader(), varIsCurlEasyResource(), varIsDBResource(), varIsGDResource(), and varIsXmlResource().
Referenced by checkType().
varIsSpecialObject (& $var)
Definition at line 334 of file dBug.php.
References varIsDBObject(), and varIsException().
Referenced by varIsObject().
varIsString (& $var)
renders string either as primitive type (if it is short (less than $embeddedStringMaxLength chars) and contains of one line) or line-by-line (otherwise)
Definition at line 232 of file dBug.php.
References closeTDRow(), makeTableHeader(), makeTDHeader(), and renderPrimitiveType().
Referenced by checkType().
varIsXml ($var)
if variable is an xml type remember, that you must force type to xml to use this
Definition at line 626 of file dBug.php.
varIsXmlResource ($var)
if variable is an xml resource type
Definition at line 631 of file dBug.php.
Referenced by varIsResource().
xmlCharacterData ($parser, $data)
xml: initiated when text between tags is encountered
Definition at line 707 of file dBug.php.
xmlDefaultHandler ($parser, $data)
xml: initiated when a comment or other miscellaneous texts is encountered
Definition at line 718 of file dBug.php.
xmlEndElement ($parser, $name)
xml: initiated when an end tag is encountered
Definition at line 689 of file dBug.php.
xmlParse ($xml_parser, $data, $bFinal)
parses xml
Definition at line 664 of file dBug.php.
xmlStartElement ($parser, $name, $attribs)
xml: inititiated when a start tag is encountered
Definition at line 673 of file dBug.php.
Field Documentation
$arrHistory = array()
Definition at line 42 of file dBug.php.
$bCollapsed = false
Definition at line 41 of file dBug.php.
Referenced by dBug(), renderPrimitiveType(), and renderTableHeader().
$bInitialized = false
shows wheither the main header for this dBug call was drawn
Definition at line 40 of file dBug.php.
$embeddedStringMaxLength =50 static
Definition at line 43 of file dBug.php.
$exceptionExcludedProps static
Initial value:
=array(
    'trace'
    )
array of properties of Exception of not to be rendered
Definition at line 571 of file dBug.php.
$exceptionMainProps =array('message','code','file','line') static
array of properties of every exception to be rendered first
Definition at line 569 of file dBug.php.
$xmlAttrib
Definition at line 35 of file dBug.php.
$xmlCData
Definition at line 31 of file dBug.php.
$xmlCount =0
Definition at line 34 of file dBug.php.
$xmlDData
Definition at line 33 of file dBug.php.
$xmlDepth =array()
Definition at line 30 of file dBug.php.
$xmlName
Definition at line 36 of file dBug.php.
$xmlSData
Definition at line 32 of file dBug.php.
The documentation for this class was generated from the following file:
dBug.php